# Generated by Django 2.0.7 on 2018-07-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='_person_collaborators_+', to='cadherin.Person')),
                ('phd_advisor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='cadherin.Person')),
                ('postdoc_advisor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='postdoc', to='cadherin.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('people', models.ManyToManyField(blank=True, to='cadherin.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
            ],
        ),
    ]
