# Generated by Django 2.0.7 on 2018-07-07 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadherin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='_person_collaborators_+', to='cadherin.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phd_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='cadherin.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='postdoc_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postdoc', to='cadherin.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, to='cadherin.Person'),
        ),
    ]
