# Generated by Django 2.0.7 on 2018-07-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadherin', '0002_auto_20180707_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phd_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='cadherin.Person'),
        ),
    ]
