# Generated by Django 2.0.7 on 2018-07-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadherin', '0003_auto_20180707_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('from_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_relations', to='cadherin.Project')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_relations', to='cadherin.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PubRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('from_pub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_relations', to='cadherin.Publication')),
                ('to_pub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_relations', to='cadherin.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='phd_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='cadherin.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='postdoc_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postdocs', to='cadherin.Person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='cadherin.Person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='cadherin.Note'),
        ),
        migrations.AddField(
            model_name='publication',
            name='related_to_pubs',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_from_pubs', through='cadherin.PubRelation', to='cadherin.Publication'),
        ),
        migrations.AddField(
            model_name='person',
            name='affiliations',
            field=models.ManyToManyField(blank=True, null=True, to='cadherin.Affiliation'),
        ),
        migrations.AddField(
            model_name='person',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='cadherin.Category'),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='cadherin.Note'),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadherin.Role'),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='cadherin.Category'),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='cadherin.Note'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_to_projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_from_projects', through='cadherin.ProjectRelation', to='cadherin.Project'),
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='cadherin.Category'),
        ),
        migrations.AddField(
            model_name='question',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='cadherin.Note'),
        ),
    ]
