# Generated by Django 2.0.7 on 2018-07-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadherin', '0004_auto_20180708_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='pm_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
