# Generated by Django 2.0.7 on 2018-07-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadherin', '0005_auto_20180708_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='display_name',
        ),
        migrations.AddField(
            model_name='publication',
            name='first_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='last_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
