# Generated by Django 2.0.7 on 2018-07-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadherin', '0007_auto_20180708_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pub_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
