# Generated by Django 2.0.7 on 2018-07-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadherin', '0008_auto_20180708_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='num_authors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
