# Generated by Django 2.0.7 on 2018-07-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadherin', '0009_publication_num_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='pub_year',
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
